<a href="https://colab.research.google.com/github/Anshul-ARK/ml_lab/blob/main/ML_lab2_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd #data preprocessing
import numpy as np #linear algebra
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/sem5/ml_assignments/ass_1/Housing.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
df.shape

(545, 13)

In [ ]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [ ]:
#first convert the values into numerical
df = df.replace({'yes':1 , 'no':0 })
#ordinal
furnish_map = {'unfurnished':0 , 'semi-furnished':1 , 'furnished':2}
df = df.replace({'furnishingstatus':furnish_map})

/tmp/ipython-input-3642241509.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'yes':1 , 'no':0 })
/tmp/ipython-input-3642241509.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'furnishingstatus':furnish_map})

In [ ]:
df.corr()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
price,1.000000,0.535997,0.366494,0.517545,0.420712,0.296898,0.255517,0.187057,0.093073,0.452954,0.384394,0.329777,0.304721
area,0.535997,1.000000,0.151858,0.193820,0.083996,0.288874,0.140297,0.047417,-0.009229,0.222393,0.352980,0.234779,0.171445
bedrooms,0.366494,0.151858,1.000000,0.373930,0.408564,-0.012033,0.080549,0.097312,0.046049,0.160603,0.139270,0.079023,0.123244
bathrooms,0.517545,0.193820,0.373930,1.000000,0.326165,0.042398,0.126469,0.102106,0.067159,0.186915,0.177496,0.063472,0.143559
stories,0.420712,0.083996,0.408564,0.326165,1.000000,0.121706,0.043538,-0.172394,0.018847,0.293602,0.045547,0.044425,0.104672
mainroad,0.296898,0.288874,-0.012033,0.042398,0.121706,1.000000,0.092337,0.044002,-0.011781,0.105423,0.204433,0.199876,0.156726
guestroom,0.255517,0.140297,0.080549,0.126469,0.043538,0.092337,1.000000,0.372066,-0.010308,0.138179,0.037466,0.160897,0.118328
basement,0.187057,0.047417,0.097312,0.102106,-0.172394,0.044002,0.372066,1.000000,0.004385,0.047341,0.051497,0.228083,0.112831
hotwaterheating,0.093073,-0.009229,0.046049,0.067159,0.018847,-0.011781,-0.010308,0.004385,1.000000,-0.130023,0.067864,-0.059411,0.031628
airconditioning,0.452954,0.222393,0.160603,0.186915,0.293602,0.105423,0.138179,0.047341,-0.130023,1.000000,0.159173,0.117382,0.150477
parking,0.384394,0.352980,0.139270,0.177496,0.045547,0.204433,0.037466,0.051497,0.067864,0.159173,1.000000,0.091627,0.177539
prefarea,0.329777,0.234779,0.079023,0.063472,0.044425,0.199876,0.160897,0.228083,-0.059411,0.117382,0.091627,1.000000,0.107686
furnishingstatus,0.304721,0.171445,0.123244,0.143559,0.104672,0.156726,0.118328,0.112831,0.031628,0.150477,0.177539,0.107686,1.000000

In [ ]:
print(tuple(df.columns))

('price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'furnishingstatus')

In [ ]:
df.sample()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
518,2450000,3500,2,1,1,1,1,0,0,0,0,0,0

In [ ]:
df.sample()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
299,4200000,7000,3,1,1,1,0,0,0,0,3,0,2

In [ ]:
#normalization
#1 Min-max scaler
# Manual min-max normalization for 'price' column
min_price = df['price'].min()
max_price = df['price'].max()
df['price'] = (df['price'] - min_price) / (max_price - min_price)
min_area = df['area'].min()
max_area = df['area'].max()
df['area'] = (df['area'] - min_area) / (max_area - min_area)

In [ ]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,1.000000,0.396564,4,2,3,1,0,0,0,1,2,1,2
1,0.909091,0.502405,4,4,4,1,0,0,0,1,3,0,2
2,0.909091,0.571134,3,2,2,1,0,1,0,0,2,1,1
3,0.906061,0.402062,4,2,2,1,0,1,0,1,3,1,2
4,0.836364,0.396564,4,1,2,1,1,1,0,1,2,0,2

In [ ]:
outlier_counts = {}
for col in df.columns:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    low_whisk = q1 - 1.5 * iqr
    high_whisk = q3 + 1.5 * iqr
    outliers = df[(df[col] < low_whisk) | (df[col] > high_whisk)]
    outlier_counts[col] = len(outliers)

print(outlier_counts)
#price is the output

{'price': 15, 'area': 12, 'bedrooms': 12, 'bathrooms': 1, 'stories': 41, 'mainroad': 77, 'guestroom': 97, 'basement': 0, 'hotwaterheating': 25, 'airconditioning': 0, 'parking': 12, 'prefarea': 128, 'furnishingstatus': 0}

In [ ]:
# For only numeric columns
corr_with_price = df.corr(numeric_only=True)['price'].sort_values(ascending=False)
print(corr_with_price)

price               1.000000
area                0.535997
bathrooms           0.517545
airconditioning     0.452954
stories             0.420712
parking             0.384394
bedrooms            0.366494
prefarea            0.329777
furnishingstatus    0.304721
mainroad            0.296898
guestroom           0.255517
basement            0.187057
hotwaterheating     0.093073
Name: price, dtype: float64

In [ ]:
#remove the outliers for more relevant columns , which interfere with mse,corr
# we dont remove the outliers of less relevant cols cause because they don’t strongly influence the target, and removing them would mean losing
# rows that are otherwise valuable for the important features.
#we remove the col outliers where corr > 0.4
high_corr_cols = ['area', 'bathrooms', 'airconditioning', 'stories']

mask = pd.Series(False, index=df.index)

for col in high_corr_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    low_whisk = q1 - 1.5 * iqr
    high_whisk = q3 + 1.5 * iqr
    mask |= (df[col] < low_whisk) | (df[col] > high_whisk)

df_clean = df[~mask]

print(f"Original rows: {df.shape[0]}")
print(f"Rows after cleaning: {df_clean.shape[0]}")

Original rows: 545
Rows after cleaning: 492

In [ ]:
Y = df_clean.iloc[:, 0]        # Select the first column as target (Price)
X = df_clean.iloc[:, 1:]       # Select the rest as features

In [ ]:
X.shape,Y.shape

((492, 12), (492,))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((393, 12), (99, 12), (393,), (99,))

In [ ]:
X_train_np = np.array(X_train, dtype=float)
y_train_np = np.array(y_train, dtype=float).reshape(-1, 1)
X_test_np = np.array(X_test, dtype=float)
y_test_np = np.array(y_test, dtype=float).reshape(-1, 1) #converting (n) into (nx1) matrix

# Add bias term (column of ones) to X_train and X_test
X_train_bias = np.c_[np.ones((X_train_np.shape[0], 1)), X_train_np]
X_test_bias = np.c_[np.ones((X_test_np.shape[0], 1)), X_test_np]

# θ = (Xᵀ X)⁻¹ Xᵀ y
theta = np.linalg.inv(X_train_bias.T.dot(X_train_bias)).dot(X_train_bias.T).dot(y_train_np)

# Predictions
y_pred_train = X_train_bias.dot(theta)
y_pred_test = X_test_bias.dot(theta)

# R² Score Function
def r2_score(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    return 1 - (ss_res / ss_tot)

# Evaluation
train_r2 = r2_score(y_train_np, y_pred_train)
test_r2 = r2_score(y_test_np, y_pred_test)

print("Model coefficients (theta):", theta.flatten())
print(f"Train R² Score: {train_r2:.4f}")
print(f"Test R² Score: {test_r2:.4f}")
#model is not overfitting as  r2_train >> r2_test.
#model performs equally well (or better) on unseen data.
#For predictive models, train R² must be close to test R² to ensure it generalizes well.

Model coefficients (theta): [-0.1289072   0.31186369  0.01262914  0.07288781  0.0343483   0.03390262
  0.03325394  0.02901619  0.07049518  0.07099414  0.01877063  0.05889717
  0.02405069]
Train R² Score: 0.6133
Test R² Score: 0.6485

In [ ]:
# Make sure we know the feature names in the same order as X_train
feature_names = X_train.columns

# Intercept (bias term)
intercept = theta[0][0]

# Coefficients for each feature
coefficients = theta[1:].flatten()

print(f"Intercept: {intercept:.4f}")
print("\nFeature Coefficients:")
for name, coef in zip(feature_names, coefficients):
    print(f"{name:20s} {coef:.4f}")

# R² scores
print(f"\nTrain R² Score: {train_r2:.4f}")
print(f"Test R² Score: {test_r2:.4f}")

Intercept: -0.1289

Feature Coefficients:
area                 0.3119
bedrooms             0.0126
bathrooms            0.0729
stories              0.0343
mainroad             0.0339
guestroom            0.0333
basement             0.0290
hotwaterheating      0.0705
airconditioning      0.0710
parking              0.0188
prefarea             0.0589
furnishingstatus     0.0241

Train R² Score: 0.6133
Test R² Score: 0.6485

In [ ]:
Y = df.iloc[:, 0]        # Select the first column as target (Price)
X = df.iloc[:, 1:]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((436, 12), (109, 12), (436,), (109,))

In [ ]:
X_train_np = np.array(X_train, dtype=float)
y_train_np = np.array(y_train, dtype=float).reshape(-1, 1)
X_test_np = np.array(X_test, dtype=float)
y_test_np = np.array(y_test, dtype=float).reshape(-1, 1) #converting (n) into (nx1) matrix

# Add bias term (column of ones) to X_train and X_test
X_train_bias = np.c_[np.ones((X_train_np.shape[0], 1)), X_train_np]
X_test_bias = np.c_[np.ones((X_test_np.shape[0], 1)), X_test_np]

# θ = (Xᵀ X)⁻¹ Xᵀ y
theta = np.linalg.inv(X_train_bias.T.dot(X_train_bias)).dot(X_train_bias.T).dot(y_train_np)

# Predictions
y_pred_train = X_train_bias.dot(theta)
y_pred_test = X_test_bias.dot(theta)

# R² Score Function
def r2_score(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    return 1 - (ss_res / ss_tot)

# Evaluation
train_r2 = r2_score(y_train_np, y_pred_train)
test_r2 = r2_score(y_test_np, y_pred_test)

print("Model coefficients (theta):", theta.flatten())
print(f"Train R² Score: {train_r2:.4f}")
print(f"Test R² Score: {test_r2:.4f}")
#model is not overfitting as  r2_train >> r2_test.
#we find that the df r2score is better than df_clean score , so the outliers might have useful value rather than noise

Model coefficients (theta): [-0.15049777  0.31963671  0.01094634  0.08684552  0.0373298   0.03766095
  0.03421634  0.02859642  0.10467236  0.07445604  0.01905513  0.06006491
  0.02213479]
Train R² Score: 0.6810
Test R² Score: 0.6578

2nd Question - Aviation Accidents/Incidents

In [ ]:
df_av = pd.read_csv('/content/drive/MyDrive/sem5/ml_assignments/ass_2/faa_ai_prelim.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_av['EVENT_LCL_TIME'] = df_av['EVENT_LCL_TIME'].str.replace('Z', '', regex=False)
#remove the Z
# Combine to Datetime
df_av['EVENT_DATETIME'] = pd.to_datetime(df_av['EVENT_LCL_DATE'] + ' ' + df_av['EVENT_LCL_TIME'],errors='coerce', format='%d-%b-%y %H:%M:%S')

In [ ]:
columns_needed = [
    'EVENT_DATETIME',
    'ACFT_MAKE_NAME',
    'LOC_STATE_NAME',
    'ACFT_MODEL_NAME',
    'RMK_TEXT',
    'FLT_PHASE',
    'EVENT_TYPE_DESC',
    'FATAL_FLAG',
    'ACFT_DMG_DESC'
]
new_df = df_av[columns_needed].copy()

In [ ]:
new_df.shape

(83, 9)

In [ ]:
new_df.info()
new_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EVENT_DATETIME   83 non-null     datetime64[ns]
 1   ACFT_MAKE_NAME   78 non-null     object
 2   LOC_STATE_NAME   83 non-null     object
 3   ACFT_MODEL_NAME  79 non-null     object
 4   RMK_TEXT         83 non-null     object
 5   FLT_PHASE        82 non-null     object
 6   EVENT_TYPE_DESC  83 non-null     object
 7   FATAL_FLAG       8 non-null      object
 8   ACFT_DMG_DESC    74 non-null     object
dtypes: datetime64[ns](1), object(8)
memory usage: 6.0+ KB

,EVENT_DATETIME,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG,ACFT_DMG_DESC
0,2016-02-19 00:45:00,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes,Unknown
1,2016-02-18 23:55:00,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN,Unknown
2,2016-02-18 22:14:00,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,NaN,Minor
3,2016-02-18 17:10:00,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,NaN,Unknown
4,2016-02-18 00:26:00,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,NaN,Minor

In [ ]:
new_df['FATAL_FLAG'] = new_df['FATAL_FLAG'].fillna('No')

In [ ]:
fill = new_df['FLT_PHASE'].mode()
mode = fill[0]
new_df['FLT_PHASE'] = new_df['FLT_PHASE'].fillna(mode)
fill1 = new_df['ACFT_DMG_DESC'].mode()
mode1 = fill1[0]
new_df['ACFT_DMG_DESC'] = new_df['ACFT_DMG_DESC'].fillna(mode1)

In [ ]:
new_df.dropna(subset=['ACFT_MAKE_NAME'], inplace=True)
new_df.dropna(subset=['ACFT_MODEL_NAME'], inplace=True)

In [ ]:
new_df.isnull().sum()

EVENT_DATETIME     0
ACFT_MAKE_NAME     0
LOC_STATE_NAME     0
ACFT_MODEL_NAME    0
RMK_TEXT           0
FLT_PHASE          0
EVENT_TYPE_DESC    0
FATAL_FLAG         0
ACFT_DMG_DESC      0
dtype: int64

In [ ]:
new_df.shape

(77, 9)

In [ ]:
airplane_name = new_df['ACFT_MAKE_NAME'].value_counts()
print(airplane_name)

ACFT_MAKE_NAME
CESSNA                    23
PIPER                     10
BEECH                      9
MOONEY                     4
BOEING                     3
BELL                       2
CHAMPION                   2
SOCATA                     2
LANCAIR                    2
GLOBE                      1
VANS                       1
CHRISTEN                   1
HUGHES                     1
FAIRCHILD                  1
CONSOLIDATED VULTEE        1
GREAT LAKES                1
SAAB                       1
MAULE                      1
EMBRAER                    1
PITTS                      1
AEROSTAR INTERNATIONAL     1
AIRBUS                     1
GRUMMAN                    1
GULFSTREAM                 1
FLIGHT DESIGN              1
AERO COMMANDER             1
SABRELINER                 1
AERONCA                    1
NORTH AMERICAN             1
Name: count, dtype: int64

In [ ]:
fatal_obs = new_df[new_df['FATAL_FLAG'] == 'Yes']
print(fatal_obs)
print(len(fatal_obs))

        EVENT_DATETIME  ACFT_MAKE_NAME  LOC_STATE_NAME ACFT_MODEL_NAME  \
0  2016-02-19 00:45:00           BEECH  North Carolina              36
53 2016-02-11 11:32:00           PIPER         Florida            PA28
55 2016-02-11 00:17:00   FLIGHT DESIGN      California            CTLS
79 2016-02-05 11:17:00  NORTH AMERICAN         Arizona             F51
80 2016-02-05 23:02:00        CHAMPION      California           8KCAB
81 2016-02-05 23:02:00           BEECH      California              35
82 2016-02-02 01:52:00          CESSNA         Alabama             182

                                             RMK_TEXT      FLT_PHASE  \
0   AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...  UNKNOWN (UNK)
53  AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...  UNKNOWN (UNK)
55  AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...  UNKNOWN (UNK)
79  AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...  UNKNOWN (UNK)
80  N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...  UNKNOWN (UNK)
81  N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...  UNKNOWN (UNK)
82  N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...  UNKNOWN (UNK)

   EVENT_TYPE_DESC FATAL_FLAG ACFT_DMG_DESC
0         Accident        Yes       Unknown
53        Accident        Yes     Destroyed
55        Accident        Yes     Destroyed
79        Accident        Yes     Destroyed
80        Accident        Yes     Destroyed
81        Accident        Yes     Destroyed
82        Accident        Yes       Unknown
7

In [ ]:
unique_cats = new_df['ACFT_DMG_DESC'].unique()
print(unique_cats)

['Unknown' 'Minor' 'Substantial' 'Destroyed']

In [ ]:
for cat in unique_cats:
    col_name = f"DMG_{cat}"
    # Fill the new column with 1 where it matches the category, else 0
    new_df[col_name] = (new_df['ACFT_DMG_DESC'] == cat).astype(int)

In [ ]:
# Example: drop the unknown category column
new_df.drop(columns=[f"DMG_Unknown"], inplace=True)
# DMG_Unknown  = 1 - (DMG_Destroyed +DMG_Minor + DMG_Substantial)
# TO AVOID MULTICOLLINEARITY

In [ ]:
new_df.sample()

,EVENT_DATETIME,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG,ACFT_DMG_DESC,DMG_Minor,DMG_Substantial,DMG_Destroyed
65,2016-02-08 18:58:00,CESSNA,Oregon,175,AIRCRAFT ON LANDING WENT OFF THE RUNWAY INTO A...,LANDING (LDG),Accident,No,Substantial,0,1,0

In [ ]:
def extract_phase(text):
    if pd.isnull(text):
        return 'UNKNOWN'
    phases = ['LANDING', 'TAKEOFF', 'CRUISE', 'APPROACH']
    for phase in phases:
        if phase in text.upper():
            return phase
    return 'UNKNOWN'

new_df['FLIGHT_PHASE_TEXT'] = new_df['RMK_TEXT'].apply(extract_phase)

In [ ]:
comparison = pd.DataFrame({
    'Original_Phase': new_df['FLT_PHASE'],
    'Text_Phase': new_df['FLIGHT_PHASE_TEXT']
})
print(comparison.head(20))

    Original_Phase Text_Phase
0    UNKNOWN (UNK)    UNKNOWN
1    LANDING (LDG)    LANDING
2   APPROACH (APR)    UNKNOWN
3    LANDING (LDG)    LANDING
4    LANDING (LDG)    LANDING
5    UNKNOWN (UNK)    UNKNOWN
6    LANDING (LDG)    LANDING
7    LANDING (LDG)    LANDING
8    TAKEOFF (TOF)    UNKNOWN
10   LANDING (LDG)    LANDING
12   LANDING (LDG)    LANDING
13   LANDING (LDG)    LANDING
14   TAKEOFF (TOF)    TAKEOFF
15   LANDING (LDG)    UNKNOWN
16   TAKEOFF (TOF)    TAKEOFF
17   LANDING (LDG)    LANDING
18   TAKEOFF (TOF)    UNKNOWN
19   LANDING (LDG)    LANDING
20   LANDING (LDG)    LANDING
21   UNKNOWN (UNK)    UNKNOWN